import { api } from "../client";

export const teacherApi = {
  dashboard: async () => (await api.get("/api/v1/teacher/dashboard")).data.data,
  sessionsToday: async () => (await api.get("/api/v1/teacher/sessions/today")).data.data,
  roster: async (sessionId: string) => (await api.get(`/api/v1/teacher/sessions/${sessionId}/roster`)).data.data,
  markAttendance: async (sessionId: string, records: Array<{ student_id: string; status: string }>) =>
    (await api.post("/api/v1/teacher/attendance/mark", { sessionId, records })).data.data,
  attendanceReports: async () => (await api.get("/api/v1/teacher/attendance/reports")).data.data,
  defaulters: async () => (await api.get("/api/v1/teacher/attendance/defaulters")).data.data,
  leaveBalance: async () => (await api.get("/api/v1/teacher/leave/balance")).data.data,
  leaveRequests: async () => (await api.get("/api/v1/teacher/leave/my-requests")).data.data,
  submitLeave: async (payload: Record<string, unknown>) => (await api.post("/api/v1/teacher/leave/request", payload)).data.data,
  affectedSessions: async (start: string, end: string) => (await api.get("/api/v1/teacher/sessions/in-daterange", { params: { start, end } })).data.data,
  uploadResource: async (payload: Record<string, unknown>) => (await api.post("/api/v1/teacher/resources/upload", payload)).data.data,
  resources: async (subject_id?: string, section_id?: string) => (await api.get("/api/v1/teacher/resources", { params: { subject_id, section_id } })).data.data,
  toggleCurrentSyllabus: async (id: string, value: boolean) => (await api.patch(`/api/v1/teacher/resources/${id}/current-syllabus`, { value })).data.data,
  deleteResource: async (id: string) => (await api.delete(`/api/v1/teacher/resources/${id}`)).data,
  createPreprep: async (payload: Record<string, unknown>) => (await api.post("/api/v1/teacher/preprep", payload)).data.data,
  getPreprep: async () => (await api.get("/api/v1/teacher/preprep")).data.data,
  getBacklog: async () => (await api.get("/api/v1/teacher/backlog")).data.data,
  getChecklist: async (sessionId: string) => (await api.get(`/api/v1/teacher/checklist/${sessionId}`)).data.data,
  submitChecklist: async (sessionId: string, items: unknown[]) => (await api.post(`/api/v1/teacher/checklist/${sessionId}/submit`, { items })).data.data,
  generateTest: async (payload: Record<string, unknown>) => (await api.post("/api/v1/teacher/tests/generate", payload)).data.data,
  tests: async () => (await api.get("/api/v1/teacher/tests")).data.data,
  test: async (id: string) => (await api.get(`/api/v1/teacher/tests/${id}`)).data.data,
  updateQuestion: async (testId: string, questionId: string, payload: Record<string, unknown>) => (await api.patch(`/api/v1/teacher/tests/${testId}/questions/${questionId}`, payload)).data.data,
  publishTest: async (id: string) => (await api.post(`/api/v1/teacher/tests/${id}/publish`)).data.data,
  testAnalytics: async (id: string) => (await api.get(`/api/v1/teacher/tests/${id}/analytics`)).data.data,
  chatSummary: async (roomId: string, date: string) => (await api.get(`/api/v1/teacher/chat/${roomId}/summary`, { params: { date } })).data.data,
  volunteerSubstitute: async (requestId: string) => (await api.post(`/api/v1/teacher/substitute/${requestId}/volunteer`)).data.data,
  volunteerSubstituteByBody: async (requestId: string) => (await api.post("/api/v1/teacher/substitute/volunteer", { requestId })).data.data,
  substituteRequests: async () => (await api.get("/api/v1/teacher/substitute/requests")).data.data,
  profile: async () => ({ name: "Dr. Arjun", employee_id: "EMP201", subjects: ["Math - CS-A"], notifications: { leave_decision: true, substitute_request: true } }),
};
